version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - $PWD/config/prometheus/prometheus-aws.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    restart: always
    networks:
      - grafana-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 80:3000
    restart: unless-stopped
    networks:
      - grafana-network

  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - minio_data_volume:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server data --address ':9000' --console-address ':9001'
    shm_size: "256mb"
    networks:
      - grafana-network

  createbuckets:
    image: minio/mc
    volumes:
      - minio_data_volume:/data
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb data/loki-aws;
      /usr/bin/mc anonymous set public data/loki-aws;
      exit 0;
      "
    networks:
      - grafana-network

  loki-aws:
    image: grafana/loki:latest
    container_name: loki-aws
    environment:
      - MINIO_ROOT_PASSWORD
      - MINIO_ROOT_USER
    ports:
      - "3100:3100"
    volumes:
      - "$PWD/config/loki/loki-aws.yml:/etc/loki/loki-config.yml"
    command: -config.file=/etc/loki/loki-config.yml -config.expand-env=true
    depends_on:
      - minio
    restart: always
    networks:
      - grafana-network

volumes:
  prometheus-data:
  grafana-data:
  minio_data_volume:

networks:
  grafana-network:
    driver: bridge
